### PR TITLE
Update Helper class

### PR DESCRIPTION
**Pull request by Pradhumn-Kamble**

### CODE REVIEW

**Review by Pradhumn-Kamble-2 — CHANGES_REQUESTED** [review]
Add one more property of 'b'

**Comment by Pradhumn-Kamble-2** [comment]
done

**Comment by Pradhumn-Kamble** [comment]
new commit pushed

**Comment by Pradhumn-Kamble-2** [comment]
checking!!!

**Comment by Pradhumn-Kamble-2** [comment]
need some changes

**Comment by Pradhumn-Kamble** [comment]
will be working on it

**Comment by Pradhumn-Kamble** [comment]
done , check

**Comment by Pradhumn-Kamble-2** [comment]
all good

**Pull request merged**
